### ISSUE TITLE
Error on sync

### ISSUE THREAD

**Issue by rmehta** [frappe/bench_manager#11]
```
Traceback (most recent call last):
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/Users/rushabh/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 203, in sync_all
    sync_apps()
  File "/Users/rushabh/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 76, in sync_apps
    doc.insert()
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 192, in insert
    self.run_before_save_methods()
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 870, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/rushabh/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/rushabh/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/app/app.py", line 24, in validate
    self.update_app_details()
  File "/Users/rushabh/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/app/app.py", line 90, in update_app_details
    if 'Version:' in data:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

**Comment by codingCoffee** [comment]
@rmehta the latest `develop` branch should fix this problem. Please update and check if its working now!
