### ISSUE TITLE
Error while opening Bench Manager

### ISSUE THREAD

**Issue by witedusa** [frappe/bench_manager#50]
Hi frappe team,
I have installed Bench Manager App in my ERPNext website, I am using Production Image of ERPNext in VirtualBox.
When ever i try to run Bench Manager I am getting below error, and form fields are disabled, also site list is empty.

```
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
>     doc.save()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
>     return self._save(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
>     self.run_before_save_methods()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
>     self.run_method("validate")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
>     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 29, in validate
>     sync_all(in_background=True)
>   File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 223, in sync_all
>     sync_sites()
>   File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 63, in sync_sites
>     site_dirs = update_site_list()
>   File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 114, in update_site_list
>     for root, dirs, files in os.walk(".", topdown=True):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 294, in walk
>     for x in walk(new_path, topdown, onerror, followlinks):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 294, in walk
>     for x in walk(new_path, topdown, onerror, followlinks):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 294, in walk
>     for x in walk(new_path, topdown, onerror, followlinks):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 284, in walk
>     if isdir(join(top, name)):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/posixpath.py", line 80, in join
>     path += '/' + b
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 1: ordinal not in range(128)
> 
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
>     data = execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
>     doc.save()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
>     return self._save(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
>     self.run_before_save_methods()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
>     self.run_method("validate")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
>     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 29, in validate
>     sync_all(in_background=True)
>   File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 223, in sync_all
>     sync_sites()
>   File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 63, in sync_sites
>     site_dirs = update_site_list()
>   File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 114, in update_site_list
>     for root, dirs, files in os.walk(".", topdown=True):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 294, in walk
>     for x in walk(new_path, topdown, onerror, followlinks):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 294, in walk
>     for x in walk(new_path, topdown, onerror, followlinks):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 294, in walk
>     for x in walk(new_path, topdown, onerror, followlinks):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 284, in walk
>     if isdir(join(top, name)):
>   File "/home/frappe/frappe-bench/env/lib/python2.7/posixpath.py", line 80, in join
>     path += '/' + b
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 1: ordinal not in range(128)
```

**Comment by mhbu50** [comment]
Try this command:

```
sudo locale-gen en_US en_US.UTF-8 hu_HU hu_HU.UTF-8
sudo dpkg-reconfigure locales
```

**Comment by codingCoffee** [comment]
@witedusa did doing the above solve the issue?

**Comment by witedusa** [comment]
@codingCoffee I already have all my locales as UTF-8, so even after running commands still i am getting the same error.
**But please note that this error is coming pre-installed ERPNext virtual machine,
I installed fresh copy of ERPNext by myself, I transfer all the database from VM ERPNext to new Real ERPNext server and bench manager is working on that.**

**Comment by federicocalvo** [comment]
Hi @witedusa @mhbu50,  Are any of you still using a bench manager today?

**Comment by justmejust** [comment]
@witedusa @mhbu50 @federicocalvo who still using Bench manager?
i go this problem 
Updating

Your system is being updated. Please refresh again after a few moments

Status: 503
